<script>
  import { showUpload, importCases, patientCount, orderCount } from '$lib/stores/app.js';
  import { parseCaseFile } from '$lib/utils/parser.js';
  import { OPUS_PROMPT } from '$lib/data/template.js';
  import { DEMO_PATIENTS, DEMO_ORDERS } from '$lib/data/demo.js';

  let result = $state(null);
  let dragging = $state(false);
  let parsed = $state(null);
  let fileInput;

  function processFile(file) {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const res = parseCaseFile(e.target.result);
        parsed = res;
        result = { ok: true, msg: `Parsed ${res.patientCount} patient(s) with ${res.orderCount} order(s)` };
      } catch (err) {
        parsed = null;
        result = { ok: false, msg: err.message };
      }
    };
    reader.readAsText(file);
  }

  function onDrop(e) {
    e.preventDefault();
    dragging = false;
    const f = e.dataTransfer.files[0];
    if (f) processFile(f);
  }

  function onChange(e) {
    const f = e.target.files[0];
    if (f) processFile(f);
  }

  function downloadTemplate() {
    const blob = new Blob([OPUS_PROMPT], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'pharmverify_opus_prompt.txt'; a.click();
    URL.revokeObjectURL(url);
  }

  function downloadSampleJSON() {
    const sample = { patients: { P100: DEMO_PATIENTS.P001 }, orders: [DEMO_ORDERS[0]] };
    const blob = new Blob([JSON.stringify(sample, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'pharmverify_sample_case.json'; a.click();
    URL.revokeObjectURL(url);
  }

  function doImport() {
    if (parsed) {
      importCases(parsed);
      showUpload.set(false);
    }
  }

  function close() {
    showUpload.set(false);
  }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="tmo" onclick={close}>
  <div class="tmb" style="width:480px" onclick={(e) => e.stopPropagation()}>
    <h3>Import Patient Cases</h3>
    <p>Upload a JSON file generated by Claude Opus with patient scenarios. Cases will be added to your existing queue ({$patientCount} patients, {$orderCount} orders).</p>

    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="upzone"
      class:drag={dragging}
      onclick={() => fileInput?.click()}
      ondragover={(e) => { e.preventDefault(); dragging = true; }}
      ondragleave={() => dragging = false}
      ondrop={onDrop}
    >
      <div class="icon">{dragging ? '\u{1F4E5}' : '\u{1F4C4}'}</div>
      <div style="font-size:13px;font-weight:500">Drop JSON file here or click to browse</div>
      <div style="font-size:13px;color:var(--t3);margin-top:4px">.json or .txt files accepted</div>
    </div>
    <input bind:this={fileInput} type="file" accept=".json,.txt" style="display:none" onchange={onChange} />

    {#if result}
      <div class="ures" class:ures-ok={result.ok} class:ures-err={!result.ok}>
        {result.ok ? '\u2713' : '\u2717'} {result.msg}
        {#if !result.ok}<pre>{result.msg}</pre>{/if}
      </div>
    {/if}

    <div style="display:flex;gap:6px;margin-bottom:14px">
      <button class="fb fb-tpl" onclick={downloadTemplate} style="flex:1">&#x1F4DD; Opus Prompt Template</button>
      <button class="fb fb-tpl" onclick={downloadSampleJSON} style="flex:1">&#x1F4CB; Sample JSON</button>
    </div>

    <div class="tma">
      <button class="btn" onclick={close}>Cancel</button>
      {#if parsed}
        <button class="btn bv" onclick={doImport}>Import {parsed.patientCount} Patient(s)</button>
      {/if}
    </div>
  </div>
</div>
